language: cpp
compiler:
  - gcc
#  - clang
before_install:
  - echo "yes" | sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
install: "sudo apt-get install qt5-qmake libqt5webkit5-dev qtdeclarative5-dev libgstreamer-plugins-base0.10-dev libxslt1-dev libgio2.0-cil-dev libgst-dev libglib2.0-dev libxml2-dev libsqlite3-dev"
script: "make"
